services:
  mysql:
    image: mysql:8.4
    container_name: personal_blog_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_blog
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: personal_blog_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:

